# configs for the quick access terminal, not regular kitty
# ~/.config/kitty/quick-access-terminal.conf
#
# https://sw.kovidgoyal.net/kitty/kittens/quick-access-terminal/
#
# this one will be important for multi-monitor: https://sw.kovidgoyal.net/kitty/kittens/quick-access-terminal/#opt-kitten-quick_access_terminal.output_name
#
# kitten quick_access_terminal tmux -f /home/ellotheth/dotfiles/tmux.conf new-session -A -s tilda

# about half at 1080p?
lines 35

# 'top' is default. it can also go other places, like the middle of the screen
# edge center-sized
# columns 200

# this is already in the parent, i don't know if it's necessary here too
background_opacity 0.9
