# configs for the quick access terminal, not regular kitty
# https://sw.kovidgoyal.net/kitty/kittens/quick-access-terminal/
#
# this one will be important for multi-monitor: https://sw.kovidgoyal.net/kitty/kittens/quick-access-terminal/#opt-kitten-quick_access_terminal.output_name
#
# kitten quick_access_terminal -c /home/ellotheth/dotfiles/kitty.conf tmux -f /home/ellotheth/dotfiles/tmux.conf new-session -A -s tilda

# about half at 1080p?
lines 35

# 'top' is default. it can also go other places, like the middle of the screen
# edge center-sized
# columns 200

background_opacity 0.8

# this doesn't work in gnome under x11 but it's probably fine on wayland
map f11 toggle_fullscreen
