# create a new session called tilda, or attach to one that already exists
# tmux -f ~/dotfiles/tmux.conf new-session -A -s tilda

# i'm not changing prefixes
set-option -g prefix C-a
unbind-key C-b
bind-key a send-prefix

# do other stuff more like screen
bind-key C-a last-window # default l
unbind &
bind C-k kill-pane
bind M-k kill-window

# notify on activity in other windows
setw -g monitor-activity on
setw -g monitor-bell on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# move around panes like vim
bind l select-pane -R
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
# move panes around like vim
bind L swap-pane -dt :."{right-of}"
bind H swap-pane -dt :."{left-of}"
bind J swap-pane -dt :."{down-of}"
bind K swap-pane -dt :."{up-of}"

# cycle through panes, `o` by default
# bind ^A select-pane -t :.+

set -g status-style bg=colour235

# quick tmux config reload
unbind R
bind R source-file ~/dotfiles/tmux.conf

# tabs in the middle, host on the left, timestamp on the right
set -g status-justify absolute-centre
set -g status-left '#[fg=brightgreen][ #H ]'
set -g status-left-length 20
set -g status-right '#[fg=brightgreen][ #[fg=brightblue]%Y-%m-%d  #[fg=white]%H:%M #[fg=brightgreen]]'
setw -g window-status-format '#I:#[fg=colour243]#W'
setw -g window-status-current-format '#I:#[fg=brightred,bold]#W'

# fix vim colors
set -g default-terminal 'screen-256color'
set -ag terminal-overrides ',xterm-256color:Tc'
